### ISSUE TITLE
GPU build stream produces dark screens when no pixels has changed

### ISSUE THREAD

**Issue by danielmalmq** [google/android-emulator-container-scripts#201]
When starting the container stack with GPU enabled the result is that the stream flickers a lot when no pixels are changing on the screen. If some animation is playing everything is running smoothly but as soon as there are no animations the screen either flickers or goes dark.

To replicate this issue from a clean master branch I perform the following commands:
```
source configure.sh
emu-docker create stable Q --gpu
./create_web_container.sh -p user1,passwd1
```

To actually start the container stack I run:
```
xhost +SI:localuser:root

docker network create envoymesh

docker run --network=envoymesh --expose 8080 --expose 8001 --expose 8443 -p 80:8080 -p 443:8443 -p 8001:8001 -d emulator_envoy
docker run --network=envoymesh --net-alias jwt_signer --expose 8080 -d emulator_jwt_signer
docker run --network=envoymesh --net-alias nginx --expose 80 -d emulator_nginx
docker run --gpus all \
-e DISPLAY \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e "TOKEN=$(cat ~/.emulator_console_auth_token)" \
-e "ADBKEY=$(cat ~/.android/adbkey)" \
-e "EMULATOR_PARAMS=-gpu host ${PARAMS}" \
--device /dev/kvm \
--network=envoymesh \
--net-alias emulator \
--publish 8554:8554/tcp \
--publish 5555:5555/tcp \
emulator_emulator
```

**Comment by copiltembel** [comment]
I'm having the same problem.

**Comment by copiltembel** [comment]
I believe it has something to do with the nvidia drivers, couldn't figure yet what.

**Comment by copiltembel** [comment]
@danielmalmq : Older versions of the Android Emulator seem to be fine (for ex. 30.0.12.0 (build_id 6466327) worked for me). The newer 30.0.26.0 (build_id 6755297) behaves as you described.

**Comment by pokowaka** [comment]
We are investigating this. It could be related to the new WebRTC engine we are using, we might need to push frames when nothing happens.

**Comment by copiltembel** [comment]
@pokowaka : Actually I like the fact that we can spare bandwidth and encoding effort by not pushing any frames if nothing has changed.

What I did is just not send the blank frames at all:

```
absl::optional<::webrtc::VideoFrame> VideoShareCapturer::getVideoFrame() {
    [...]
    if (IsBlank(mI420Buffer.get())) { // could actually do this before the call to libyuv::ConvertToI420
        // Blank frame, return empty
        return {};
    } else {
        // NOT BLANK
    }
    return ::webrtc::VideoFrame::Builder()
            .set_video_frame_buffer(mI420Buffer)
            .set_timestamp_rtp(0)
            .set_timestamp_us(rtc::TimeMicros())
            .set_rotation(::webrtc::kVideoRotation_0)
            .build();
}

static bool IsBlank(::webrtc::I420Buffer* buf) {
    return *buf->DataY() == 16 &&
           *buf->DataU() == 128 &&
           *buf->DataV() == 128;
}
```

This works fine most of the time (unsure now if the reason for other weird behaviour is this).

I know that this is 1. ugly and 2. inefficient and 3. might not be true if the screen goes blank intentionally, but for me it's a temporary workaround.

**Comment by copiltembel** [comment]
So couldn't we instead just not increase the VideoInfo's frameNumber if nothing has changed?

**Comment by pokowaka** [comment]
The system (should) work as follows:

- Whenever android produces a new frame we copy the frame to a shared memory region and increase the frame counter.
- We only feed the encoder a new frame if the frame counter has increased, (or if we just start a connection).

The fact that you need this work around implies that:

- The frame counter is increasing, so android must think it produced a frame
- We are incorrectly producing a black frame in case of inactivity.

In this case the primary suspect is this change:

https://android-review.googlesource.com/c/platform/external/qemu/+/1294595

**Comment by pokowaka** [comment]
Would you be willing/able to share the docker logs? I want to make sure it is not related to a shared memory closing down to early issue.

**Comment by danielmalmq** [comment]
Here are the logs as requested 
[containers.zip](https://github.com/google/android-emulator-container-scripts/files/5266028/containers.zip)

**Comment by pokowaka** [comment]
Thank you. Nothing unusual/unexpected on the logs. Locally I'm unable to reproduce this :-(.  We just fixed a related [bug](https://android-review.googlesource.com/c/platform/external/qemu/+/1434672), but that is likely not what you are seeing.

Do you happen to have an APK that demonstrates when this happens, and do you happen to know which GPU you are using?

**Comment by copiltembel** [comment]
For me there's no particular APK for which this happens. It happens at the system level (ex. when booting up, the screen flickers; when boot completes, there's just a black image unless something changes on the screen, etc.).

I also get the same behaviour without the docker container. My initial quess was that there's a problem with the Nvidia drivers, so I tried an older version (390) but the flickering was still there. 

My GPU is a Quadro K2200 and driver version 450.66 (cuda 11.0).

Did something change in the OpenGL rendering layer used by the emulator recently?

**Comment by danielmalmq** [comment]
Yeah "[WebRTC] Fix black screen after reconnect" does not sound like the same bug as it is not reconnecting as far as I can tell.

There are no special apks or similar used, this a straight from the master branch of the repo with a clean gpu version of the android system without any modifications.

Recorded a video showing the issue: https://youtu.be/Zs4CFlKiY1s

I am using an ubuntu 20.04 system with the following gpu: NVIDIA Corporation GM108M [GeForce 940MX] (rev a2).

And as @copiltembel mentioned it does work as intended if I roll back the qemu to the old build 6466327

**Comment by pokowaka** [comment]
@danielmalmq  thank you for sharing. It is clear that this is broken. @copiltembel if this happens without the container than we can exclude the change I mentioned above as it is not related to the webrtc infrastructure and it would indeed point to something that is not working as expected in the rendering layer.

@copiltembel  Would you mind filing an issue here: https://issuetracker.google.com/issues/new?component=192708&template=840533 that will make it easier to get people from the emulator team to have a look at it. (Just let me know the bugid and I will follow up internally).

**Comment by copiltembel** [comment]
@pokowaka Done: https://issuetracker.google.com/issues/169343630

**Comment by danielmalmq** [comment]
Hey hey, any news relating to the GPU issue? Thanks

**Comment by copiltembel** [comment]
Yes, would be great to get some feedback on it. 

Unfortunately after trying the emu-master-dev version it looks like this is not fixed yet.

Because this is really bugging me and I'd like to experiment making changes in the emulator, I'd like to build an older version of the emulator. For example version 30.0.12.0 doesn't have this problem, but I don't know how to download & build this particular version. How can I do this?

**Comment by danielmalmq** [comment]
It is now working when running canary builds, nice work!

**Comment by copiltembel** [comment]
I've just built the emu-master-dev branch, but the problem doesn't seem to be solved there yet.

**Comment by copiltembel** [comment]
@danielmalmq Which version are you using that doesn't have this behavior?

**Comment by danielmalmq** [comment]
Fixed from 30.5.0, retested with latest canary 30.6.3 and there it also works as intended.

Getting ~30fps reported in chrome://webrtc-internals when playing a fullhd youtube video in chrome.
```

**Comment by copiltembel** [comment]
Unfortunately I still see the same behavior on 30.06.1.0 on a Quadro P2200

`emulator: Android emulator version 30.6.1.0 (build_id ) (CL:N/A)`

```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P2200        Off  | 00000000:01:00.0  On |                  N/A |
| 51%   45C    P8     5W /  75W |    325MiB /  5057MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       887      G   /usr/lib/xorg/Xorg                 55MiB |
|    0   N/A  N/A      1180      G   /usr/bin/gnome-shell               78MiB |
|    0   N/A  N/A      5042    C+G   ...mu-system-x86_64-headless      180MiB |
+-----------------------------------------------------------------------------+
```
